In [36]:
import pandas as pd
import numpy as np
import matplotlib as plt

In [37]:
df = pd.read_csv ("Iris.csv")
df.head

x = df.iloc[:,:-1].values
y = df.iloc[:,-1].values

In [38]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

from sklearn.neighbors import KNeighborsClassifier

In [39]:
classifier = KNeighborsClassifier(n_neighbors=5)
classifier.fit (x_train, y_train)

y_pred = classifier.predict(x_test)

In [40]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        11
Iris-versicolor       1.00      0.92      0.96        13
 Iris-virginica       0.86      1.00      0.92         6

       accuracy                           0.97        30
      macro avg       0.95      0.97      0.96        30
   weighted avg       0.97      0.97      0.97        30



In [41]:
from sklearn.metrics import confusion_matrix, accuracy_score
print("Confusion Matrix : \n", confusion_matrix(y_test, y_pred))

Confusion Matrix : 
 [[11  0  0]
 [ 0 12  1]
 [ 0  0  6]]


In [42]:
yp = [[6.7, 4.9, 3, 1.4]]
print(classifier.predict(yp))
accuracy = accuracy_score(y_test, y_pred)
print(accuracy)

['Iris-setosa']
0.9666666666666667
